# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Bump Version
        working-directory: ./radar-render
        run: |
          npm version ${{github.event.release.tag_name}}
          git commit --amend --message "Nuevo mensaje del commit"
          git push --force
      - name: Install Dependencies
        working-directory: ./radar-render
        run: npm ci
      - name: Build
        working-directory: ./radar-render
        run: npm run build
      - name: Publish Package
        working-directory: ./radar-render
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
